---

- project:
    name: 'jenkins jobs'
    job-description: '<h4 style="color:#999696;">Deploy jenkins jobs</h4>'
    jobs:
#      - '{name} deploy'
      - 'jobs_uploader'
      - 'ui_tests'
      - 'api_tests'
      - 'appium_tests'